import 'package:flutter/material.dart';
import './models/category.dart';
import './models/meal.dart';
const dummyCategories =  [
  Category(id: 'c1', title: 'Italian',color: Colors.purple),
  Category(id: 'c2', title: 'Quick & Easy',color: Colors.red),
  Category(id: 'c3', title: 'Hamburgers',color: Colors.yellowAccent),
  Category(id: 'c4', title: 'German',color: Colors.yellow),
  Category(id: 'c5', title: 'Light & Lovely',color: Colors.blue),
  Category(id: 'c6', title: 'Exotic',color: Colors.lightGreen),
  Category(id: 'c7', title: 'Breakfast',color: Colors.lightBlue),
  Category(id: 'c8', title: 'Asian',color: Colors.lightBlueAccent),
];
var dummyMeals = [
  Meal(
    id: 'm1',
    duration: 25,
    affordability: Affordability.pricey,
    categories: ['c5','c6'],
    complexity: Complexity.simple,
    imageUrl: 'kfjfjf',
    ingredients: ['fjord','flak'],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegeterian: false,
    steps: ['argv','okay'],
    title: 'mode',
  ),
  Meal(
    id: 'm2',
    duration: 25,
    affordability: Affordability.pricey,
    categories: ['c3','c4'],
    complexity: Complexity.simple,
    imageUrl: 'kfjfjf',
    ingredients: ['fjord','flak'],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegeterian: false,
    steps: ['argv','okay'],
    title: 'node',
  ),
  Meal(
    id: 'm3',
    duration: 25,
    affordability: Affordability.pricey,
    categories: ['c1','c2'],
    complexity: Complexity.simple,
    imageUrl: 'kfjfjf',
    ingredients: ['fjord','flak'],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegeterian: false,
    steps: ['argv','okay'],
    title: 'modes',
  ),
  Meal(
    id: 'm4',
    duration: 25,
    affordability: Affordability.pricey,
    categories: ['c7','c8'],
    complexity: Complexity.simple,
    imageUrl: 'kfjfjf',
    ingredients: ['fjord','flak'],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegeterian: false,
    steps: ['argv','okay'],
    title: 'nodes',
  ),
];